services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose API port
      - "8188:8188" # Expose UI port
    # ipc: host
    # ulimits:
    #   memlock: -1
    #   stack: 67108864
    volumes:
      #   # Optional: mount local directories for persistence
      #   - ./output:/src/output # For generated images/videos
      #   - ./input:/src/input # For input files
      - ./models:/src/models # For model weights
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # entrypoint: [ "sleep", "infinity" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped
